export const htmlStyles = `
    :root {
      --bg-primary: #f8fafc;
      --bg-card: #ffffff;
      --text-primary: #0f172a;
      --text-secondary: #475569;
      --border-color: #e2e8f0;
      --color-indigo: #6366f1;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      background-color: var(--bg-primary);
      color: var(--text-primary);
      line-height: 1.5;
      padding: 40px 20px;
      margin: 0;
    }

    .container {
      max-width: 1000px;
      margin: 0 auto;
      background: var(--bg-card);
      border: 1px solid var(--border-color);
      border-radius: 12px;
      padding: 40px;
      box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.05);
    }

    h1 {
      font-size: 28px;
      margin-top: 0;
      margin-bottom: 8px;
      color: var(--text-primary);
      display: flex;
      align-items: center;
      gap: 10px;
    }

    .subtitle {
      color: var(--text-secondary);
      font-size: 14px;
      margin-bottom: 30px;
      border-bottom: 1px solid var(--border-color);
      padding-bottom: 20px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 24px;
      font-size: 13px;
    }

    th, td {
      padding: 10px 12px;
      text-align: left;
      border-bottom: 1px solid var(--border-color);
    }

    th {
      background-color: #f1f5f9;
      color: var(--text-secondary);
      font-weight: 600;
    }

    tr:hover {
      background-color: #f8fafc;
    }

    code {
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      background-color: #f1f5f9;
      padding: 2px 5px;
      border-radius: 4px;
      font-size: 12px;
      color: #0f172a;
    }

    .badge {
      display: inline-block;
      font-size: 9px;
      font-weight: 700;
      padding: 2px 5px;
      border-radius: 4px;
      text-transform: uppercase;
    }

    .badge-pk {
      background-color: #fef3c7;
      color: #d97706;
      border: 1px solid #fde68a;
    }

    .badge-fk {
      background-color: #d1fae5;
      color: #059669;
      border: 1px solid #a7f3d0;
    }

    .table-section {
      margin-top: 40px;
      border-top: 1px solid var(--border-color);
      padding-top: 30px;
    }

    .table-title {
      font-size: 20px;
      margin-top: 0;
      color: var(--text-primary);
    }

    .sql-box {
      background-color: #0f172a;
      color: #f8fafc;
      border-radius: 8px;
      padding: 16px;
      position: relative;
      margin-top: 12px;
      overflow-x: auto;
    }

    .sql-box pre {
      margin: 0;
    }

    .sql-box code {
      background: none;
      color: #e2e8f0;
      padding: 0;
    }

    .copy-btn {
      position: absolute;
      top: 10px;
      right: 10px;
      background: rgba(255, 255, 255, 0.1);
      border: 1px solid rgba(255, 255, 255, 0.2);
      color: #f8fafc;
      border-radius: 4px;
      padding: 4px 8px;
      font-size: 11px;
      cursor: pointer;
      transition: background 0.15s ease;
    }

    .copy-btn:hover {
      background: rgba(255, 255, 255, 0.2);
    }

    @media print {
      body {
        background-color: #fff;
        padding: 0;
      }
      .container {
        border: none;
        box-shadow: none;
        padding: 0;
      }
      .sql-box, .copy-btn {
        display: none !important;
      }
      .table-section {
        page-break-inside: avoid;
      }
    }
`;

export function getHtmlBase(tableRows: string, tableSections: string, schemaLength: number): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Database Documentation Report</title>
  <style>${htmlStyles}</style>
</head>
<body>
  <div class="container">
    <h1>
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: var(--color-indigo);">
        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
        <polyline points="14 2 14 8 20 8"></polyline>
        <line x1="16" y1="13" x2="8" y2="13"></line>
        <line x1="16" y1="17" x2="8" y2="17"></line>
        <polyline points="10 9 9 9 8 9"></polyline>
      </svg>
      Database Schema Report
    </h1>
    <div class="subtitle">
      Generated by DataLens Flow on ${new Date().toLocaleDateString()} | Total Tables: <strong>${schemaLength}</strong>
    </div>

    <h2>Table of Contents</h2>
    <table>
      <thead>
        <tr>
          <th style="width: 30%;">Table Name</th>
          <th style="width: 15%;">Columns</th>
          <th style="width: 25%;">Primary Key(s)</th>
          <th style="width: 30%;">Foreign Keys</th>
        </tr>
      </thead>
      <tbody>
        ${tableRows}
      </tbody>
    </table>

    ${tableSections}
  </div>
</body>
</html>`;
}
